CREATE VIEW VIEW_USER_INFORMATION AS
SELECT USERS.USER_ID, USERS.FIRST_NAME, USERS.LAST_NAME,USERS.YEAR_OF_BIRTH,USERS.MONTH_OF_BIRTH, USERS.DAY_OF_BIRTH, USERS.GENDER,
CURR.CITY_NAME AS CURRENT_CITY, CURR.STATE_NAME AS CURRENT_STATE, CURR.COUNTRY_NAME AS CURRENT_COUNTRY,
HOME.CITY_NAME AS HOMETOWN_CITY, HOME.STATE_NAME AS HOMETOWN_STATE, HOME.COUNTRY_NAME AS HOMETOWN_COUNTRY,
PROGRAMS.INSTITUTION AS INSTITUTION_NAME, EDUCATION.PROGRAM_YEAR, PROGRAMS.CONCENTRATION AS PROGRAMS_CONCENTRATION, PROGRAMS.DEGREE AS PROGRAMS_DEGREE
FROM USERS
LEFT JOIN USER_CURRENT_CITIES ON USER_CURRENT_CITIES.USER_ID = USERS.USER_ID
LEFT JOIN CITIES CURR ON USER_CURRENT_CITIES.CURRENT_CITY_ID = CURR.CITY_ID
LEFT JOIN USER_HOMETOWN_CITIES ON USERS.USER_ID = USER_HOMETOWN_CITIES.USER_ID
LEFT JOIN CITIES HOME ON USER_HOMETOWN_CITIES.HOMETOWN_CITY_ID = HOME.CITY_ID
LEFT JOIN EDUCATION ON USERS.USER_ID = EDUCATION.USER_ID
LEFT JOIN PROGRAMS ON EDUCATION.PROGRAM_ID = PROGRAMS.PROGRAM_ID;


CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT FRIENDS.USER1_ID, FRIENDS.USER2_ID
FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT ALBUMS.ALBUM_ID, ALBUMS.ALBUM_OWNER_ID AS OWNER_ID, ALBUMS.COVER_PHOTO_ID, ALBUMS.ALBUM_NAME, ALBUMS.ALBUM_CREATED_TIME, ALBUMS.ALBUM_MODIFIED_TIME, ALBUMS.ALBUM_LINK, ALBUMS.ALBUM_VISIBILITY, 
PHOTOS.PHOTO_ID, PHOTOS.PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTOS.PHOTO_MODIFIED_TIME, PHOTOS.PHOTO_LINK
FROM ALBUMS, PHOTOS
WHERE ALBUMS.ALBUM_ID = PHOTOS.ALBUM_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT DISTINCT TAGS.TAG_PHOTO_ID AS PHOTO_ID, TAGS.TAG_SUBJECT_ID, TAGS.TAG_CREATED_TIME, TAGS.TAG_X AS TAG_X_COORDINATE, TAGS.TAG_Y AS TAG_Y_COORDINATE
FROM TAGS;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT USER_EVENTS.EVENT_ID, USER_EVENTS.EVENT_CREATOR_ID, USER_EVENTS.EVENT_NAME, USER_EVENTS.EVENT_TAGLINE, USER_EVENTS.EVENT_DESCRIPTION, USER_EVENTS.EVENT_HOST, USER_EVENTS.EVENT_TYPE AS EVENT_TYPE, USER_EVENTS.EVENT_SUBTYPE,
USER_EVENTS.EVENT_ADDRESS, CITIES.CITY_NAME AS EVENT_CITY, CITIES.STATE_NAME AS EVENT_STATE, CITIES.COUNTRY_NAME AS EVENT_COUNTRY, USER_EVENTS.EVENT_START_TIME, USER_EVENTS.EVENT_END_TIME
FROM USER_EVENTS, CITIES
WHERE USER_EVENTS.EVENT_CITY_ID = CITIES.CITY_ID;




