INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
SELECT DISTINCT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM project1.PUBLIC_USER_INFORMATION;

INSERT INTO FRIENDS (USER1_ID, USER2_ID)
SELECT DISTINCT USER1_ID, USER2_ID
FROM project1.PUBLIC_ARE_FRIENDS;

INSERT INTO CITIES (CITY_NAME, STATE_NAME, COUNTRY_NAME)
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY
FROM project1.PUBLIC_USER_INFORMATION
UNION
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY
FROM project1.PUBLIC_USER_INFORMATION
UNION
SELECT DISTINCT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY
FROM project1.PUBLIC_EVENT_INFORMATION;

INSERT INTO USER_CURRENT_CITIES (USER_ID, CURRENT_CITY_ID)
SELECT DISTINCT USERS.USER_ID, CITIES.CITY_ID
FROM USERS, CITIES, project1.PUBLIC_USER_INFORMATION p1
WHERE USERS.USER_ID = p1.USER_ID
AND CITIES.CITY_NAME = p1.CURRENT_CITY
AND CITIES.STATE_NAME = p1.CURRENT_STATE
AND CITIES.COUNTRY_NAME = p1.CURRENT_COUNTRY;

INSERT INTO USER_HOMETOWN_CITIES (USER_ID, HOMETOWN_CITY_ID)
SELECT DISTINCT USERS.USER_ID, CITIES.CITY_ID
FROM USERS, CITIES, project1.PUBLIC_USER_INFORMATION p1
WHERE USERS.USER_ID = p1.USER_ID
AND CITIES.CITY_NAME = p1.HOMETOWN_CITY
AND CITIES.STATE_NAME = p1.HOMETOWN_STATE
AND CITIES.COUNTRY_NAME = p1.HOMETOWN_COUNTRY;

INSERT INTO PROGRAMS (INSTITUTION, CONCENTRATION, DEGREE)
SELECT DISTINCT INSTITUTION_NAME, PROGRAM_CONCENTRATION, PROGRAM_DEGREE
FROM project1.PUBLIC_USER_INFORMATION
WHERE INSTITUTION_NAME IS NOT NULL
AND PROGRAM_CONCENTRATION IS NOT NULL
AND PROGRAM_DEGREE IS NOT NULL;

INSERT INTO EDUCATION (USER_ID, PROGRAM_ID, PROGRAM_YEAR)
SELECT DISTINCT USERS.USER_ID, PROGRAMS.PROGRAM_ID, p1.PROGRAM_YEAR
FROM USERS, PROGRAMS, project1.PUBLIC_USER_INFORMATION p1
WHERE USERS.USER_ID = p1.USER_ID
AND PROGRAMS.INSTITUTION = p1.INSTITUTION_NAME
AND PROGRAMS.CONCENTRATION = p1.PROGRAM_CONCENTRATION
AND PROGRAMS.DEGREE = p1.PROGRAM_DEGREE;

INSERT INTO USER_EVENTS (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, EVENT_CITY_ID, EVENT_START_TIME, EVENT_END_TIME)
SELECT DISTINCT EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, CITIES.CITY_ID, EVENT_START_TIME, EVENT_END_TIME
FROM project1.PUBLIC_EVENT_INFORMATION p1
LEFT JOIN CITIES ON p1.EVENT_CITY = CITIES.CITY_NAME
LEFT JOIN CITIES ON p1.EVENT_STATE = CITIES.STATE_NAME
LEFT JOIN CITIES ON p1.EVENT_COUNTRY = CITIES.COUNTRY_NAME;

SET AUTOCOMMIT OFF
INSERT INTO ALBUMS (ALBUM_ID, ALBUM_OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, COVER_PHOTO_ID)
SELECT DISTINCT ALBUM_ID, OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, COVER_PHOTO_ID
FROM project1.PUBLIC_PHOTO_INFORMATION;

INSERT INTO PHOTOS (PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
SELECT DISTINCT PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK
FROM project1.PUBLIC_PHOTO_INFORMATION;
COMMIT
SET AUTOCOMMIT ON

INSERT INTO TAGS (TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y)
SELECT DISTINCT PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE
FROM project1.PUBLIC_TAG_INFORMATION;