CREATE TABLE Students
    (SID INTEGER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Major VARCHAR2(100));

CREATE TABLE Projects
    (PID INTEGER PRIMARY KEY,
    P_Name VARCHAR2(100) NOT NULL,
    UNIQUE (P_Name));

CREATE TABLE Courses
    (CID INTEGER PRIMARY KEY,
    C_Name VARCHAR2(100) NOT NULL,
    UNIQUE (C_Name));

CREATE TABLE Members
    (PID INTEGER,
    SID INTEGER,
    PRIMARY KEY (PID, SID),
    FOREIGN KEY (SID) REFERENCES Students,
    FOREIGN KEY (PID) REFERENCES Projects);

CREATE TABLE Enrollments
    (CID INTEGER,
    SID INTEGER,
    PRIMARY KEY (CID, SID),
    FOREIGN KEY (CID) REFERENCES Courses,
    FOREIGN KEY (SID) REFERENCES Students);
