SELECT Courses.CID 
FROM Courses
LEFT JOIN 
(SELECT E.CID, COUNT(*) AS TOTAL_NUMBER, SUM(CASE WHEN S.MAJOR = 'CS' THEN 1 ELSE 0 END) AS CS_NUMBER
FROM Enrollments E, Students S
WHERE E.SID = S.SID
GROUP BY E.CID
) E0
ON Courses.CID = E0.CID
WHERE E0.TOTAL_NUMBER - E0.CS_NUMBER <10
ORDER BY Courses.CID DESC;
