-- Query 3: 
(SELECT E0.SID
FROM Enrollments E0, Courses C
WHERE E0.CID = C.CID
AND C.C_Name = 'EECS442'
INTERSECT
SELECT E0.SID
FROM Enrollments E0, Courses C
WHERE E0.CID = C.CID
AND C.C_Name = 'EECS445'
INTERSECT
SELECT E0.SID
FROM Enrollments E0, Courses C
WHERE E0.CID = C.CID
AND C.C_Name = 'EECS492')
UNION
(SELECT E0.SID
FROM Enrollments E0, Courses C
WHERE E0.CID = C.CID
AND C.C_Name = 'EECS482'
INTERSECT
SELECT E0.SID
FROM Enrollments E0, Courses C
WHERE E0.CID = C.CID
AND C.C_Name = 'EECS486')
UNION
(SELECT E.SID
FROM Enrollments E
INNER JOIN Courses C ON C.CID = E.CID
WHERE C.C_Name = 'EECS281');